version: "3.2"
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  ### Nginx ##############################################
  nginx:
    container_name: ${APP_CONTAINER_NAME}-web
    build:
      context: ./docker/nginx
      args:
        - CONTAINER_NAME_PHP=${APP_CONTAINER_NAME}-phpfpm
    volumes:
      - type: bind
        source: ${APP_CODE_PATH_HOST}/back
        target: ${APP_CODE_PATH_CONTAINER}/back
      - type: bind
        source: ${APP_CODE_PATH_HOST}/front
        target: ${APP_CODE_PATH_CONTAINER}/front
      - ${BASE_LOG_PATH}/nginx/:/var/log/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/ssl/:/etc/nginx/ssl
    working_dir: ${APP_CODE_PATH_CONTAINER}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - phpfpm
    networks:
      frontend:
        aliases:
          - api.localhost
      backend:
        aliases:
          - api.localhost

  ### PHP-FPM ##############################################
  phpfpm:
    container_name: ${APP_CONTAINER_NAME}-phpfpm
    build:
      context: ./docker/phpfpm/
      args:
        - PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - type: bind
        source: ${APP_CODE_PATH_HOST}/back
        target: ${APP_CODE_PATH_CONTAINER}/back
      - type: bind
        source: ${APP_CODE_PATH_HOST}/front
        target: ${APP_CODE_PATH_CONTAINER}/front
      - ./docker/phpfpm/conf/php.ini-development:/usr/local/etc/php/php.ini
    working_dir: ${APP_CODE_PATH_CONTAINER}
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - backend
    restart: "no"

  ### MriaDB ##############################################
  mariadb:
    container_name: ${APP_CONTAINER_NAME}-mariadb
    image: mariadb:${MARIADB_VERSION}
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ${MARIADB_PATH_SOURCE}
        target: /var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      - backend
    restart: "no"

  ### MailDev ##############################################
  maildev:
    container_name: ${APP_CONTAINER_NAME}-maildev
    build: ./docker/maildev
    ports:
      - "${MAILDEV_HTTP_PORT}:80"
      - "${MAILDEV_SMTP_PORT}:25"
    networks:
      - frontend
      - backend
